# Generated by Django 4.1.2 on 2022-10-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmid', models.CharField(max_length=150)),
                ('domeid', models.CharField(max_length=50)),
                ('deviceid', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PCBDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcbid', models.CharField(max_length=50)),
                ('pcbboardversion', models.CharField(max_length=50)),
                ('atmega', models.CharField(max_length=50)),
                ('esp32', models.CharField(max_length=50)),
                ('deviceid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcbboardversion', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('transport', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pcbid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.pcbdevice')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcbboardversion', models.CharField(max_length=50)),
                ('espchipid', models.CharField(max_length=50)),
                ('atmegachipid', models.CharField(max_length=50)),
                ('rgbsingleled', models.CharField(max_length=50)),
                ('ssrtrigger', models.CharField(max_length=50)),
                ('waterlevel', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('rtctimecheck', models.CharField(max_length=50)),
                ('rtctimecheckafterreset', models.CharField(max_length=50)),
                ('rybvoltege', models.CharField(max_length=50)),
                ('solenoidfeedback', models.CharField(max_length=50)),
                ('triggerbutton', models.CharField(max_length=50)),
                ('startingcurrent', models.CharField(max_length=50)),
                ('loadoncurrent', models.CharField(max_length=50)),
                ('loadoffcurrent', models.CharField(max_length=50)),
                ('currentteststatus', models.CharField(max_length=50)),
                ('espatmegacom', models.CharField(max_length=50)),
                ('espled', models.CharField(max_length=50)),
                ('espreset', models.CharField(max_length=50)),
                ('atmegareset', models.CharField(max_length=50)),
                ('atmegaresetbutton', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pcbid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.pcbdevice')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('changefrom', models.CharField(max_length=50)),
                ('changeto', models.CharField(max_length=50)),
                ('farmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.farm')),
                ('pcbid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.pcbdevice')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.config')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=50)),
                ('hprange', models.CharField(max_length=50)),
                ('dome', models.CharField(max_length=50)),
                ('deviceid', models.CharField(max_length=50)),
                ('operationtest', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('farmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.farm')),
                ('pcbid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.pcbdevice')),
            ],
        ),
        migrations.CreateModel(
            name='BasicTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcbboardversion', models.CharField(max_length=50)),
                ('visualcheck', models.CharField(max_length=50)),
                ('continuity', models.CharField(max_length=50)),
                ('powersupply', models.CharField(max_length=50)),
                ('atmega', models.CharField(max_length=50)),
                ('esp32', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pcbid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.pcbdevice')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcbboardversion', models.CharField(max_length=50)),
                ('deviceid', models.CharField(max_length=50)),
                ('wiring', models.CharField(max_length=50)),
                ('continuity', models.CharField(max_length=50)),
                ('esp32programming', models.CharField(max_length=50)),
                ('atmegaprog', models.CharField(max_length=50)),
                ('startertype', models.CharField(max_length=50)),
                ('setconfig', models.CharField(max_length=50)),
                ('selenoidtestfeedback', models.CharField(max_length=50)),
                ('loadtest', models.CharField(max_length=50)),
                ('rybcurrent', models.CharField(max_length=50)),
                ('button', models.CharField(max_length=50)),
                ('rtc', models.CharField(max_length=50)),
                ('loadtesttimermin', models.CharField(max_length=50)),
                ('loadtesttimeronoff', models.CharField(max_length=50)),
                ('statusparam', models.CharField(max_length=50)),
                ('errorcode', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pcbid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.pcbdevice')),
            ],
        ),
    ]
