# Generated by Django 4.1.2 on 2022-10-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EekiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcbid', models.CharField(max_length=50)),
                ('pcbboardversion', models.CharField(max_length=50)),
                ('atmega', models.CharField(max_length=50)),
                ('esp32', models.CharField(max_length=50)),
                ('deviceid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('changefrom', models.CharField(max_length=50)),
                ('changeto', models.CharField(max_length=50)),
                ('farmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.farm')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.config')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceTrack',
        ),
    ]
