# Generated by Django 4.1.2 on 2022-10-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EekiApp', '0002_device_delete_devicetrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblytest',
            name='pcbid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.device'),
        ),
        migrations.AlterField(
            model_name='basictest',
            name='pcbid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.device'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='pcbid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.device'),
        ),
        migrations.AlterField(
            model_name='functionaltest',
            name='pcbid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.device'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='pcbid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.device'),
        ),
        migrations.DeleteModel(
            name='PCBDevice',
        ),
    ]
