# Generated by Django 4.1.2 on 2022-10-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EekiApp', '0003_alter_assemblytest_pcbid_alter_basictest_pcbid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True)),
                ('changefrom', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='changefrom',
        ),
        migrations.RemoveField(
            model_name='device',
            name='changeto',
        ),
        migrations.RemoveField(
            model_name='device',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EekiApp.changestatus', to_field='status'),
        ),
    ]
